builder:
    ssh_sops_ed25519_key: ENC[AES256_GCM,data:WjuKSe3qE8722VcpU5TAm9X2w46K7WdHwOQ//jb0urQE7JZMVcbsrYW1339SsQPcZd/pXmqaRyAwt0a6fqxX7lY5gm2ERWiMJkGKJ/W22SdPusosTNnttjThOnG+tXztH/e8wrO9vAIx1mbASNrEqqafraTTHNMoiG4IBoqwbcaSuuVTTJmalhhpmwRqjm+JYoi9NNtTnDrnyZyCbNA2mcvNQZVirf2fjcZhAqGevlqtcQpcjdyhwcH2Anp0JfXwe/hjbT+ohJZbO1RsNnI+25xYT3/U0OxVyhZUu2+dWt4rX52u/F2dDxRSmRHlj+ziMuYItMotV6pVSRaAPDQxSf/ZV0/5+J1auvRmVlRxDtuaMT77Pfwke+zNL0VJfrM4EjBUzbf1YZ/Q66vBCmrTy7OCrnqTkLy9rAGrHW3eJEB442ZdF4IzY5tBat9DYS7a1S2mbj9G/bvLkL1a2zKEct4ehPSfVyqAU8OhnkwppJJJUsrohtIiGPi3ce1yFq8S55wAOOOhO1XfoyZ7Ryj9,iv:OLh/ygMC6/A7tOIzJqPjmw712SAXEspzJqNuW6J1HTc=,tag:Tzg0StoK1hU1c9rzjp4Bng==,type:str]
    ssh_builder_ed25519_key: ENC[AES256_GCM,data:ckDHyfx0MD8jXOecR028xcwxpaCfLrDhzwFC+RQRgELB6MybUaLuZxt2iC2S22ym7XRKoR+IshfM9MmuoaCVfoXUNEV56PRqRUwyJHrwyqvIuEGSqUa9fphAZV+nwvDmbsJq3e5/C/F6CaHgTwsGzn6u7vlXVVieCsmRphB2oaqzkQKb3zQ/DDK76x0KMJICYhKz4MmenXZtaqtobCXJT/g1bNgPQ1AZb8g/uh2Fmedv5SBQzC66hlv1/M2NR5d2QhiwzHKxbxJ5KIW7oIQhL+AspB1zYAyo3kfepEn1mHL5YCbhWhAevUJQRuu+j4UwZVYmcydIK8cxCjqVgrYDz5uh5iVRayniICVIlgbOCpRI8EkfkUR6Ewap6R+yF+mvbHRGeAtEVyORk6XEtwOho5r9iyviM4eCedXW793welXYmw0Z1D9/cARO6ZwYfUNQ15X9p3DgShxCNnDyUNtdN1k8RiJfh9cROWOjMh+MYrEUqvAjoxpGtC0QXO7Ht1Pk3IexMtXSpkOWZ9N6DYVe,iv:VkT8tbg/Oc1F2Il73WywGlofs5dnY0OhLx+mdGVT23w=,tag:C48MxcB10Nra3yo1oM743Q==,type:str]
    ssh_nixos_ed25519_key: ENC[AES256_GCM,data:QqTtgrHFz06owEd5CclXSk1P1vkyrJhN7W9rP/JfI8AmPp8XTuf90f/mohhi54t/5hALkWAtQIVBuaYyx4pgyBeKzlyiNS4/iU3akp4CQaN58Iy3BUTSLpFgQJp8lO0SXotaDpsFNZqh/4zszquuGGragmBRWgTxJpg/HiO2bgZkAu3KpidWNlveIrJeGFfIv+Q/UalH9gGUyPYyq1ffieZ8Kfj9ztnwpsN1/04KsE6wZ9wejTM5qW0egdVG39fS/1bdk4L4NPiRhS4p5Eqsml/H8tKLGDz+AeOpYPK8/pf2U23+UZErNv2kkOf+yz+P77BrVjTpKni9ZnJIkKb082+PAyhxyd8x9F/bOmAypdFL1oOgvJ7iooIAnSzWfHG3IGenIQnTb9hd5Qomu5p8w7RYfXFXCAFjxIsWLwwyguInFYle7VVKSj/7hj1VBsXQfZk33wPC4/Eis5NMDWlV5Xyj+xBLoSm2a4GqmvkLKWgx60tuZy8YKCcNmWQJV7Fd1NBrk+pPQU90fTTDJCaE,iv:skZaGt4P6h+95VCnETZEZSYMMwSMm//uHu1/4nG8Glo=,tag:Ph8sYA2Rr5GisTPa31C4Qw==,type:str]
sops:
    age:
        - recipient: age14keqxfdkualn3ez68y9flvspkyp4tqw43cn2sj6ar2tde5myc98qguqf8w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSEtmWnFNSVlFUm1SaFVC
            N1NmWFg5N0U5aERyQTZnblNDMndMc29iM3hFCnlLQkFFb0NNYnh5TEc5S2k5djQ2
            ay9HQWJpT1NYZnpPWFFuT1ZDcWZkSGcKLS0tIEduSkxiZmZ4NEQ2QlRtbVVJdmVr
            MUNZcW5DOGlUeWhpcERmaGJjZ2JvclEKcv1CocC31KX69vII7s2xmo3udOk5bOwE
            5b26ZXYUJ0i8iE3Ue5BjOVR2Jc45khMQ2NhJjDE0HyL9sgjQMG4cBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3dc5xkaz0s4rdaxnzh5thq3xmkwuddcvemw6uagppjvl7pxyvaqh0ky7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SUVmeC9HMXZ1QSsxUGxx
            QkszcTdCRWlpT0ZqdURCM2NCaVpuUFQxQUFRCjlKY3RocWZkSW9oajgyRHF1M29D
            aFowQ25sT3RmZmhEL3RIbUpYVlZhMmcKLS0tIHZyS0xPanE4MCtuaU40dTdIMy9C
            amx6V3B1NDNQc3R2MnRPcFR3VDZERW8KXESL6bC4GQW8iEsjPneelB6qaArg3TA9
            QEnCRzRZ54QtcIvxbjT/Bo9IzMAH87Gqva8GNkXQFXbaAR+ELJrm+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1773nn8we8n5yhn5qtneawstzw0wrhtd6zlkxvglj3tjgdlhc65tqllpjwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bHFDaEpvcllGcnVvWmYw
            VnhrSnZoSTRXUFk0QlZMWUZNUGpCaDY4WG44CnlzYktPK1c3NE1tcE4yNkNRcldT
            SFZSYitud2RYZVpzTmZYcDVRa05kVVkKLS0tIDAxcHlYNTdIZytxa2tCTFF1UUM5
            ZjRjM1BhUmhXQmpoLzNwVE5WMXNxdGsKo0n91VO5qIPosa4LwJyRabut0Jf+fd3u
            BFrb0JIek+8OB94z7242qdqu721+a7MI1mc2ITpQZsie0so5JshCxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T23:59:01Z"
    mac: ENC[AES256_GCM,data:DhbbEa+L42BceSRoLhfjXSdZtppNXHiBkqnGnT9HSd7TKR/bINjzyw/lVP40p7IGBXAZA7/YjC15koRriwGt25AxTqujg26qf+S1Zh1XET1TVWnxQtz141jfFMHm+SNO/PCgOWFRrMtMZUcQSeGtsKTMZ6LlUgDBlBM4KEcUYTM=,iv:wF5plC5GZuOrS5YlOvz2aMHM0VMZPkHYld5TJPD+PIA=,tag:bceb689PVaBb7gQkEgg46A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
