nix:
    github_pat: ENC[AES256_GCM,data:6N+2dfkgaLI0+Ad0wnNJGn+nVjCncSe4MCU2ZP++2tJIk1ZtbEna7LIRbv4IcJAbsZxDYegXFBZ8VHIDWXAwUzQ6b84APV4eWlk7skSdGMethmApp7PoLp9SsPayj/nJu+jfJz/MXmQQt0QMX3sL8leagRjXoeGn,iv:nW/nLMVpU9RYNcOrWYLdKTvXy0Ojf5P2iUWrQPOdHe0=,tag:7htiHMUbsPWhvwbKP7KBDA==,type:str]
sops:
    age:
        - recipient: age1r3dc5xkaz0s4rdaxnzh5thq3xmkwuddcvemw6uagppjvl7pxyvaqh0ky7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeXZaK3AyM3pJaVd4VCtl
            aHJtZnFuNGphMlpPbVE5SmRtSU1wY0szUm1ZCk5MM25DcVU3azEwUFEzV1FFaEg2
            cFhUbnFwVlcreVlhYXJ6RGtsUlMvSWMKLS0tIDVNK0o0c0lsWFM3QnhYQWFwV1V3
            TjFnNC93QVo4WmZYUjJtTjhMNTBkMDgKpfu6OaNJjoabk/7sSmQet81cdmtPt/BL
            LZ4zAbZ4WgqfFWHFC1hqL7WMt7Q1iySXL1GhrAuE6K1GFC4iU+eq2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vxnqczfrhgn0h8zaeyetup6m66lc5cac8whs72c66ewz4qxjagvqx5ue7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQm5tOUVKZitES3A2dk5F
            YjNPT1BSRUkyNmsyaHlIMnF3VlRIajFzaVQwCmczeVk1MDNObzVMUmY4SXhzL3Rj
            ZkhDemtXbHFrZm54czdWeTMzNmxUMW8KLS0tIG1XTUhqK3lsdU5sdnREWnZsNHJR
            NzJIZmlsTEt3ZVd2ejkvdzVjN0hGWXcKEFsZKJ7dufz5gus9BYndqQltfGuj22YN
            w2Ma2D5lUlAa54BysE9EfZAubItHDJEJVtSI/qb2FcVuEHeW//7/NQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tyw703k7tal82ehp4zhr6rzfrzhtv0s5cerwh2gedkt97pz4l4ksg2gykk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZU2ZTN0l4NHpJSll6T2Fx
            WGxYdGNLRkhTRGpGY05wVmdrTnVlVFpmUjFBCjVGdUpYQkgvSU9QUDNFdlc5SXo4
            ZVVob0IvSmhKd29BbkdSZGVQOUY3R0kKLS0tIEZhM1AxVURXc3NVYzdnQXF5Ry9i
            cEFDVVBqYmZ6dmlUcTN4TXVxeEs3a3cKoewPt3tCz6gk5+wH+2uli4tNj2JeAuSA
            ImtO108xe1lxxmNQ/A/7MyaWn/gKzLFSZOVxSRggNUG9Xfx8hbLRuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1773nn8we8n5yhn5qtneawstzw0wrhtd6zlkxvglj3tjgdlhc65tqllpjwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QjJPMVFIVXlwOXJkNkYx
            eTRkczd3NElqYWRkc2NyZ0lYcWoxL1dPa1E4CkFOK0FGdWI2b0dFWjFJN3hqbmJl
            M2VYMnZ6NkxVRTRab05aUy80ZE9qcGMKLS0tIHdBMTBGazVkZk00bTI1WEZ5cVFi
            ZXdtUXdPdXdIV3E3S1VGTUQvNzl1RU0KAwQyhRAG+3geyS1LwrZB3GoRUHM6x2Gt
            rPINRMC5i0i4qK91iXkfAUI2zTNdas3tM9ZDjFVfbJKLFmmuKsxipQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14keqxfdkualn3ez68y9flvspkyp4tqw43cn2sj6ar2tde5myc98qguqf8w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRE5kRTJLUlh3ck5nclJk
            L1c1S0ZnWSs3OFMzbVZJNm5DLzBIaFdXWVVBCmFncFZNaFJJK0pFdExtejF0di91
            RXplN2xMU043RTNkcFZYQkdwU3RaTTQKLS0tIFM0MUtzMm1mYS9TeGgycVJRRVFX
            K0R1c3NVS1lsNEsxbm5haXUvWDE2MEUK+8ZunwrVMznwFE5TPTmPVK3Tz8VkFKst
            EmI98KsoErqMdZ9JQqzsCULtNNO0wWrX3atXdzfgB7S10bKNkP5dfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T20:08:10Z"
    mac: ENC[AES256_GCM,data:NtoA1jXkH06tnCs9iIw2UX2lBmC2KtRzxBGVY4PI17zBuTpLecBVmUT83dPUGDqAIUo1f0TxZffBzBjjvIXiYhbUq6Kaj7gl1OJ+BZOXua2JlMzIfEgUGZLxELfAbDZyXbH2l1BI4buKETZju7XXFdghZDSjMJEA2s6YsNP1Zmo=,iv:ZJDSAY6pcQZ8tz12zF+6xAQp9M8KgNsZlVoN+F3S71w=,tag:aIJCgB5BGPAiT+uIzuJarg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
